#!/usr/bin/env python3
"""
build.py — converts src/*.txt card files into a CrowdAnki JSON deck.
Run: python3 build.py
Output: deck/GCSE Revision.json
"""

import json
import os
import glob
import hashlib
import re
import sys

SRC_DIR = "src"
OUT_DIR = "deck"
DECK_NAME = "GCSE Revision"
DECK_ID = 1_900_000_001  # stable arbitrary ID


def make_guid(text: str) -> str:
    """Stable GUID from card content — same card always gets same GUID."""
    h = hashlib.md5(text.encode("utf-8")).digest()
    # CrowdAnki uses base91-like encoding; we use base62 for simplicity
    chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
    result = ""
    n = int.from_bytes(h[:8], "big")
    while n:
        result = chars[n % 62] + result
        n //= 62
    return result.zfill(10)[:10]


def deck_id_from_name(name: str) -> int:
    """Stable integer deck ID from deck name."""
    return int(hashlib.md5(name.encode()).hexdigest()[:8], 16)


def parse_txt_file(path: str):
    """Parse a tab-separated Anki txt file, return list of card dicts."""
    cards = []
    with open(path, encoding="utf-8") as f:
        lines = f.readlines()

    for line in lines:
        line = line.rstrip("\n")
        if line.startswith("#") or not line.strip():
            continue
        parts = line.split("\t")
        if len(parts) < 4:
            continue
        notetype, field1, field2, deck_path = parts[0], parts[1], parts[2], parts[3]
        cards.append({
            "notetype": notetype.strip(),
            "field1": field1.strip(),
            "field2": field2.strip(),
            "deck_path": deck_path.strip(),
        })
    return cards


def make_note_models():
    """Return CrowdAnki note model definitions for Basic and Cloze."""
    basic = {
        "__type__": "NoteModel",
        "crowdanki_uuid": "basic-gcse-v1",
        "css": ".card { font-family: Arial; font-size: 16px; text-align: left; padding: 10px; } .front { font-weight: bold; }",
        "flds": [
            {"name": "Front", "ord": 0, "sticky": False, "rtl": False, "font": "Arial", "size": 20},
            {"name": "Back",  "ord": 1, "sticky": False, "rtl": False, "font": "Arial", "size": 20},
        ],
        "latexPost": "\\end{document}",
        "latexPre": "\\documentclass[12pt]{article}\n\\special{papersize=3in,5in}\n\\usepackage{amssymb,amsmath}\n\\pagestyle{empty}\n\\setlength{\\parindent}{0in}\n\\begin{document}\n",
        "name": "Basic (GCSE)",
        "req": [[0, "any", [0]]],
        "sortf": 0,
        "tags": [],
        "tmpls": [{
            "afmt": "{{FrontSide}}<hr id=answer>{{Back}}",
            "bafmt": "",
            "bqfmt": "",
            "did": None,
            "name": "Card 1",
            "ord": 0,
            "qfmt": "{{Front}}",
        }],
        "type": 0,
        "vers": [],
    }

    cloze = {
        "__type__": "NoteModel",
        "crowdanki_uuid": "cloze-gcse-v1",
        "css": ".card { font-family: Arial; font-size: 16px; text-align: left; padding: 10px; } .cloze { font-weight: bold; color: #0070c0; }",
        "flds": [
            {"name": "Text",  "ord": 0, "sticky": False, "rtl": False, "font": "Arial", "size": 20},
            {"name": "Extra", "ord": 1, "sticky": False, "rtl": False, "font": "Arial", "size": 20},
        ],
        "latexPost": "\\end{document}",
        "latexPre": "\\documentclass[12pt]{article}\n\\special{papersize=3in,5in}\n\\usepackage{amssymb,amsmath}\n\\pagestyle{empty}\n\\setlength{\\parindent}{0in}\n\\begin{document}\n",
        "name": "Cloze (GCSE)",
        "req": [[0, "any", [0]]],
        "sortf": 0,
        "tags": [],
        "tmpls": [{
            "afmt": "{{cloze:Text}}<br><br>{{Extra}}",
            "bafmt": "",
            "bqfmt": "",
            "did": None,
            "name": "Cloze",
            "ord": 0,
            "qfmt": "{{cloze:Text}}",
        }],
        "type": 1,
        "vers": [],
    }
    return basic, cloze


def build_deck_tree(all_cards):
    """
    Build nested deck structure from deck_path strings like
    'English Lit::Paper 1::Macbeth'
    Returns root deck dict in CrowdAnki format.
    """
    # Root deck
    root = {
        "__type__": "Deck",
        "crowdanki_uuid": "gcse-root-v1",
        "deck_configurations": [{
            "__type__": "DeckConfig",
            "crowdanki_uuid": "gcse-config-v1",
            "name": "Default",
            "new_cards_per_day": 20,
            "reviews_per_day": 200,
        }],
        "desc": "GCSE Revision deck — English, Geography, Science. Generated by build.py.",
        "dyn": 0,
        "name": DECK_NAME,
        "crowdanki_uuid": "gcse-root-v1",
        "children": [],
        "notes": [],
        "note_models": list(make_note_models()),
    }

    # Map deck_path -> deck node
    deck_map = {"": root}

    def get_or_create_deck(path: str):
        if path in deck_map:
            return deck_map[path]
        parts = path.split("::")
        parent_path = "::".join(parts[:-1])
        parent = get_or_create_deck(parent_path)
        new_deck = {
            "__type__": "Deck",
            "crowdanki_uuid": f"gcse-{make_guid(path)}",
            "desc": "",
            "dyn": 0,
            "name": parts[-1],
            "children": [],
            "notes": [],
        }
        parent["children"].append(new_deck)
        deck_map[path] = new_deck
        return new_deck

    basic_model, cloze_model = make_note_models()

    for card in all_cards:
        deck = get_or_create_deck(card["deck_path"])
        guid = make_guid(card["field1"] + card["deck_path"])

        if card["notetype"] == "Basic":
            note = {
                "__type__": "Note",
                "crowdanki_uuid": guid,
                "fields": [card["field1"], card["field2"]],
                "flags": 0,
                "guid": guid,
                "note_model_uuid": "basic-gcse-v1",
                "tags": [],
            }
        else:  # Cloze
            note = {
                "__type__": "Note",
                "crowdanki_uuid": guid,
                "fields": [card["field1"], card["field2"]],
                "flags": 0,
                "guid": guid,
                "note_model_uuid": "cloze-gcse-v1",
                "tags": [],
            }
        deck["notes"].append(note)

    return root


def main():
    print("Building CrowdAnki deck from src/ files...")

    txt_files = sorted(glob.glob(os.path.join(SRC_DIR, "*.txt")))
    if not txt_files:
        print(f"ERROR: No .txt files found in {SRC_DIR}/")
        sys.exit(1)

    all_cards = []
    for path in txt_files:
        cards = parse_txt_file(path)
        all_cards.extend(cards)
        print(f"  {os.path.basename(path)}: {len(cards)} cards")

    print(f"\nTotal: {len(all_cards)} cards from {len(txt_files)} files")

    deck = build_deck_tree(all_cards)

    os.makedirs(OUT_DIR, exist_ok=True)
    out_path = os.path.join(OUT_DIR, f"{DECK_NAME}.json")
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(deck, f, indent=2, ensure_ascii=False)

    print(f"\nOutput: {out_path}")
    print("Done! Import via Anki > File > CrowdAnki: Import from disk > select deck/ folder")


if __name__ == "__main__":
    main()
